version: '2'
services:
  db:
    image: mysql:5.6
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dealdb
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    ports:
      - 3308:3306
  app:
    image: deal/app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8086:8086
    environment:
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=dealdb
      - DATABASE_PORT=3306
